version: "3"
services:
  mongo:
    container_name: mongoDB
    image: mongo
    ports:
      - "27017:27017"
  app:
    container_name: Lender_app
    restart: always
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    env_file: .env
    ports:
      - "4220:4220"
    expose:
      - "4220"
    links:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
  test:
    build:
      context: .
      dockerfile: ./docker/test/Dockerfile
    env_file: .env
    links:
      - mongo
    container_name: lender_test
networks:
  lender:
    driver: bridge
